### ISSUE TITLE
Add in picture counting bot to Stage 1. See checklist below

### ISSUE THREAD

**Issue by wadek2** [ExtraLudic/DaedalusLabrynthV2#39]

**Comment by wadek2** [comment]
- [ ] When the correct animal button sequence is entered, the bot adds everyone to a channel and messages "upload pictures here."

- [ ] When you upload an image. You get a menu asking where this image was taken. 

- [ ] When the player submits the image bot tells everyon how many images are left for that location. E.g. 1 of 7 images for Boston Common Statue.

- [ ] When all image locations are uploaded. The bot sends a message with the code for the safe. No more messages are allowed in this channel.

**Comment by esalling23** [comment]
@barrettand check the menu in image_tag on the submit - if the number of actions (menu options) multiplied by 6 is equal to the number of uploaded images, then send the win message
